service: server-functions-image-upload

custom:
  bucket: image-upload-serverless
 
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stackName: fileUploaderHome
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}/*"
functions:
  UploadFileHome:
    handler: fileUploaderHome.handler
    events:
      - http:
          path: upload
          method: post
          cors: true
    environment:
      Bucket: ${self:custom.bucket} 
resources:
  Resources:
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucket}